### ISSUE TITLE
Protocol details

### ISSUE THREAD

**Issue by CylonicRaider** [kaliumxyz/instant-connection#2]
As the developer and maintainer of Instant, let me remark the following points about the protocol:

- There is no `part` command; one quits by simply disconnecting.
- The `identity` packet is sent exactly once and as the very first one into a client's connection; there is no specific reply to broadcasting one's nick beyond the general aptly-named `reply`.
- Although, as of CylonicRaider/Instant@5313c8f41dc9f330cbf382f0b5885df830896f5a, there actually exists a command for actively enumerating other clients, nicknames are still handled peer-to-peer only. To be reliably present on the nick list, a client ought to both broadcast its nick when it connects and/or changes its nick, *and* actively reply to `who` broadcasts by other clients (ideally by sending a `nick` unicast back, to avoid spamming others).

**Comment by kaliumxyz** [comment]
This issue will remain for the time being till the protocol is fully implemented and tested for every feature.

**Comment by kaliumxyz** [comment]
Most of these have been fixed since 0.2.0 kaliumxyz/instant-connection@7b15b4213d975dff4ccf4ac5f387794b26e3443d
Problems with the unicast not being directed still exist and will be fixed with version 0.4.0, as the current version is likely broken due to changes to Instant itself.
