### ISSUE TITLE
memory leak on event handlers

### ISSUE THREAD

**Issue by kaliumxyz** [kaliumxyz/instant-connection#4]
Same problem as with euphoria-connection, likely cause is the websocket lib.

**Comment by kaliumxyz** [comment]
The issue is caused by adding too many event listeners rapidly, one should not add more than one at a time.
UWS solves this issue, I recommend we switch to that.

**Comment by kaliumxyz** [comment]
@CylonicRaider proposed an elegant solution:
![awesome](https://i.imgur.com/Vf13lMV.png)

**Comment by CylonicRaider** [comment]
That's... a workaround, not a solution.

**Comment by kaliumxyz** [comment]
A workaround can be a solution, else I doubt much of the internet would work :smiley:

**Comment by CylonicRaider** [comment]
Let's say it's not ~the best~ a *good* solution.

**Comment by kaliumxyz** [comment]
I implemented @CylonicRaider his solution in commit ce13b7b this issue has been fixed for instant-connection (I'll open another issue for euphoria-connection).
